### PR TITLE
Add Dutch labels for latest version

### PR DESCRIPTION
**Pull request by laurianvm**

### CODE REVIEW

**Comment by laurianvm** [comment]
Only dutch speaking people can actually review, 
mainly adding Giorgia and Alessandro for a heads up this is being added,

**Comment by giorgialodi** [comment]
@laurianvm I see a failure here in pushing this PR. Could you please check that?

**Comment by laurianvm** [comment]
@cedricdcc you know more about the action, do you know what is failing?

**Comment by cedricdcc** [comment]
> @cedricdcc you know more about the action, do you know what is failing?

The error in the workflow run occurs because the `github-push-action` is trying to push changes to the `main` branch. However, the push fails since the remote `main` branch contains changes that aren't in the local branch from which the action is running. 

The message in the workflow log simply indicates that `main` contains updates that our workflow doesn't have locally, but it doesn't affect the PR itself.

SO we are all good when we merge 👍

**Comment by mpo-vliz** [comment]
> The error in the workflow run occurs because the `github-push-action` is trying to push changes to the `main` branch. However, the push fails since the remote `main` branch contains changes that aren't in the local branch from which the action is running.
> 
> The message in the workflow log simply indicates that `main` contains updates that our workflow doesn't have locally, but it doesn't affect the PR itself.
> 
> SO we are all good when we merge 👍

@cedricdcc , (I think) I understand - but it is not very welcoming to the rest of the people involved that in-depth inside information of the inner workings of any workflow action is needed to be able to assess the meaning / relevance of its reported failures ? 

The typical contract and procedure here is to have CI failures flag PR's that should not be merged, so streamlining that process to the fullest we should not falsly flag PR as being bad, if they are not?

If there is a way to alter that github action (maybe in this very PR) to make sure this push to main only happens when executed on main so to avoid this confusion, that would be grand.

@giorgialodi - to be clear:
- there is no problem with out of sync branches - if that would be the case, one would not be able to even execute the merge (which we can) 
- the error-flagging we see here comes from the CI workfow execution and is to be considered a false negative (some detail:
  - the workflow uses pylode to make an html (web-publishable) variant of the ontology-turtle, and does so within the context of the executed branch (the one of this PR)
  - it then commits that html directly to the *main* branch. 
  - but when performing that in the non-main branch (context of this PR) it yields this error 
  - IMHO, this last step should simply not be tried in this pr-non-main-branch case, but only be effective after the actual merge to main) 
- I suggest @cedricdcc to investigate such a fix -- if that would take him too long with could safely merge already, and just flag a new issue for this to be resolved in the coming weeks

**Review by mpo-vliz — CHANGES_REQUESTED** [review]
see https://github.com/MareGraph-EU/assets/pull/2#issuecomment-2443768653

**Review by mpo-vliz — CHANGES_REQUESTED** [review]
please resolve conflicts

**Pull request merged**
